module.exports = {
   'if': 'IfStatement',
   'for': 'ForStatement',
   'block': 'BlockStatement',
   'true': 'true',
   'false': 'false',
   'switch': 'SwitchStatement',
   'case': 'SwitchCase',
   'expr': 'ExpressionStatement',
   'cond_split': ', and ',
   'func_dec': 'FunctionDeclaration',
   'func_expr': 'FunctionExpression',
   'cb_error': 'error',
   'cb_success': 'success',
   'cb_on': {
      'type': 'Identifier',
      'name': 'on',
   },
   'call': 'CallExpression',
   'identifier': 'Identifier',
   'var_dec': 'VariableDeclaration',
   'return': 'ReturnStatement',
   'mem_expr': 'MemberExpression',
   'literal': 'Literal',
}
